### ISSUE TITLE
Any plans of a Firefox extension?

### ISSUE THREAD

**Issue by yashendra2797** [fcannizzaro/com.dim.streamdeck#10]
Hey there! I love this entire app, but I was wondering if there were any plans to make a Firefox extension?

Thanks!

**Comment by fcannizzaro** [comment]
Right now there is no plan to write a Firefox extension. In the future perhaps.

**Comment by yashendra2797** [comment]
Thanks! Could this extension be updated to work with Microsoft Edge Perhaps since its a Chromium browser as well?
