### ISSUE TITLE
DIM Integration Discussion

### ISSUE THREAD

**Issue by SunburnedGoose** [fcannizzaro/com.dim.streamdeck#13]
Hey there, I'm Rick, one of the maintainers of DIM. Congratulations on making this extension. Folks have been asking for ages to see one made. 

I'd like to catch up with you about this effort. Where's a good place to talk? Discord, Email, Twitter DM? I would prefer to send you an invite to our slack where our team collaborates.

**Comment by stayupthetree** [comment]
This. Please this.

**Comment by fcannizzaro** [comment]
Yep, asap I'll write you where we can talk. Probably next week because I'll have more free time.

**Comment by jeffbaldwinjr** [comment]
Can this be a collaboration with the community? I would love to help out as well.

**Comment by SunburnedGoose** [comment]
We've noticed that the extension is activating the refresh button in the browser very frequently. Too frequently. We need to talk about how often this should occur.

**Comment by stayupthetree** [comment]
> We've noticed that the extension is activating the refresh button in the browser very frequently. Too frequently. We need to talk about how often this should occur.

Is this why DIM acts funky sometimes. Like I will transfer an item, then a few seconds later the screen will look like I didn't, but then revert back to where I did. Or when Im trying to read the stats on an item, and the pop up disappears constantly way too fast annoying me

**Comment by stayupthetree** [comment]
Additionally I get a lot of use out of this Steam Deck plugin, but am afraid it wont be actively worked on. There hasn't been an update in a month or so.

**Comment by fcannizzaro** [comment]
> 

Hi. is this an issue ?

**Comment by WildrCard** [comment]
> 

not for me. My issue is the loadouts on DIM, they dont show, and after trying to redo them, i lost all of them so it doesnt work at all.

**Comment by fcannizzaro** [comment]
> > 
> 
> not for me. My issue is the loadouts on DIM, they dont show, and after trying to redo them, i lost all of them so it doesnt work at all.

Hi i fixed these issues in a new version but I don't know when it will be published, I can try to update also the chrome extension meanwhile.

**Comment by WildrCard** [comment]
> 

Do you know when the new version will be available? xx
