### ISSUE TITLE
Metrics show nothing

### ISSUE THREAD

**Issue by AcidWeb** [fcannizzaro/com.dim.streamdeck#17]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/3713734/160760719-7eaaa8aa-b978-4894-abc7-f823fb136f6e.png">

**Comment by fcannizzaro** [comment]
Do you have this enabled ?

![image](https://user-images.githubusercontent.com/6225939/160920391-a03de18f-60cb-4a66-8bca-803fc5e59d62.png)

![image](https://user-images.githubusercontent.com/6225939/160920416-384af723-79c0-4ec9-ab53-2e81911ec616.png)

Right now it uses bungie api without user authentication in the metrics actions

**Comment by AcidWeb** [comment]
Yes.

<img width="884" alt="image" src="https://user-images.githubusercontent.com/3713734/160922172-cf4bcabe-6e3f-4a21-b9c1-33a28e118064.png">
