### ISSUE TITLE
Loadouts not selectable

### ISSUE THREAD

**Issue by kiyros** [fcannizzaro/com.dim.streamdeck#23]
![image](https://user-images.githubusercontent.com/43042517/169598916-138afea8-4204-4a0c-8a6c-92e12d75833e.png)
The loadouts for each character aren't showing me any options to select a loadout like it used to

**Comment by 13devin** [comment]
I've been having the same issue. Tried completely uninstalling the extension and plugin, then reinstalling both but that didn't help.

**Comment by oneole** [comment]
same here

**Comment by ferasious** [comment]
same problem, Nice plugin but please fix this issue and thank you

**Comment by r2duenas** [comment]
any update to this yet?

**Comment by LugalofKos** [comment]
I'm having the same issue. The loadout dropdown seems to have disappeared - definitely different from just refreshing and updating to repopulate because that issue could be fixed before. This seems persistent. 
![image](https://user-images.githubusercontent.com/106779896/171745996-27537317-3fee-4c72-a646-1da3f10550bb.png)

**Comment by WildrCard** [comment]
Please fix this issue, this feature was a great part of why I got the Stream Deck in the first place. Now all my loadouts are gone.

**Comment by WildrCard** [comment]
I don't understand the update, I installed it but nothing happened.

**Comment by DMC3535** [comment]
Same issue ..... bought steam deck for this feature any update ????

**Comment by fcannizzaro** [comment]
> **Notice** (from 1.0.5 release)
Right now this plugin works only using a local instance of DIM https://github.com/fcannizzaro/DIM/tree/stream-deck-integration.
 
Yesterday I created a pr on DIM to discuss the Stream Deck integration.

**Comment by ferasious** [comment]
> > **Notice** (from 1.0.5 release)
> > Right now this plugin works only using a local instance of DIM https://github.com/fcannizzaro/DIM/tree/stream-deck-integration.
> 
> Yesterday I created a pr on DIM to discuss the Stream Deck integration.

so only what we have to do now is waiting right? and thank you

**Comment by WildrCard** [comment]
Still doesnt work :(

**Comment by LugalofKos** [comment]
I downloaded the **com.dim.streamdeck.streamDeckPlugin** file, still no luck. now it says "The plugin is not enabled or DIM is closed" - definitely have DIM open, and have had the plugin downloaded/enabled. 
![image](https://user-images.githubusercontent.com/106779896/174883972-142ef354-da90-48f0-8265-409fdbf31e59.png)

**Comment by fcannizzaro** [comment]
I'm following the Stream Deck Integration while adding new features to the newer version,

@LugalofKos are you using https://github.com/fcannizzaro/DIM/tree/stream-deck-integration ?

**Comment by LugalofKos** [comment]
> 

Thanks for the reply man much appreciated! What do i need to grab from that page? I've tried the browser based DIM instance, as well as a local version. My apologies for any misunderstandings on my end, I'm still working on learning my way around GitHub.

**Comment by LugalofKos** [comment]
> for anyone who wants to try the latest version (1.0.6):
> 
> * do you have already Node.js and npm installed ? https://nodejs.org/en/
> * clone and run DIM local and configure the dev instance
> 
> ```shell
> git clone --branch stream-deck-integration https://github.com/fcannizzaro/DIM.git
> cd DIM
> yarn && yarn start
> ```
> 
> * you can go to DIM settings and enable the Stream Deck plugin

thanks man - turns out I'd need an API key and everything, from DIM and Bungie. I'll just hold off till future releases, thanks anyways!

**Comment by WildrCard** [comment]
Any news on when this will be available again?

**Comment by fcannizzaro** [comment]
You can follow this pr https://github.com/DestinyItemManager/DIM/pull/8501 to see the state of the integration
