### ISSUE TITLE
Some buttons/actions don't seem to function and trouble refreshing

### ISSUE THREAD

**Issue by agbaber** [fcannizzaro/com.dim.streamdeck#3]
Ok, so now that I've gotten the chance to play with it a bit, some more questions/feedback:

- Right now I can only get the stats to refresh by quitting Streamdeck completely and relaunching it. Should the "Refresh DIM" button work to reload the values or is that to trigger a refresh in DIM in chrome?
- All the "Action" buttons don't seem to work (refresh DIM, open DIM, equip loadout)
- Can't get some of the stat/value numbers to work properly:

Works:
- glimmer
- power total
- vanguard

doesn't work
- postmaster (shows 0/21 when its not)
- crucible
- ascendant shards
- enhancement prisms

I'm not seeing any errors in the logs anymore, but I also don't see DIM plugin-specific logs. Maybe those need to be manually enabled?

**Comment by fcannizzaro** [comment]
> Right now I can only get the stats to refresh by quitting Streamdeck completely and relaunching it. Should the "Refresh DIM" button work to reload the values or is that to trigger a refresh in DIM in chrome?

it triggers the DIM refresh in the browser (that is anyways done every 15s / 30s to keep the max power level always updated)

> All the "Action" buttons don't seem to work (refresh DIM, open DIM, equip loadout)

mmm how this is possibile, I need more checking about this. 
- The loadout action shows the available loadouts for each character at least ?
- Farming mode work ? 

It's so strange that every action work flawless in my stream deck 😕

> Can't get some of the stat/value numbers to work properly

Gambit, Trials, Battle Pass level work ? Crucible and Vanguard metrics are the same type.

> doesn't work
> postmaster (shows 0/21 when its not)
> ascendant shards
> enhancement prisms

Do you have a closed privacy on bungie.net in the Destiny section ? These params are auto-extracted from the Bungie API and not from the DIM page.  Considers that I use these actions when farming GM nightfalls to prevent to lost everything keeped in the Postmaster 🤣.

Next update I can try to extract them directly from the DIM page, if the privacy mode is enabled.

**Comment by agbaber** [comment]
> The loadout action shows the available loadouts for each character at least ?

Yep (in the streamdeck dropdowns)

> Farming mode work ?

Yep!

> All the "Action" buttons don't seem to work (refresh DIM, open DIM, equip loadout)

What the heck - these just started working (they definitely were not working before).

> Gambit, Trials, Battle Pass level work ? Crucible and Vanguard metrics are the same type.

Yep - I am a fool and didn't realize I had just reset my Crucible, so the value displayed ("0") was in fact correct. All of these work perfectly.

> Do you have a closed privacy on bungie.net in the Destiny section ? These params are extracted from the Bungie API and not from the DIM's page. Considers that I use these actions when farming GM nightfalls to prevent to lost everything keeped in the Postmaster 🤣.

Yep, I was not showing "all inventory" - this works now!


> it triggers the DIM refresh in the browser (that is anyways done every 15s / 30s to keep the max power level always updated)

Understood. That seems to be working now. Still not sure how I can refresh some of the values (like max power) without restarting streamdeck.

**Comment by fcannizzaro** [comment]
> Understood. That seems to be working now. Still not sure how I can refresh some of the values (like max power) without restarting streamdeck.

Ah ok I'll check during the grind in TWQ if it works correctly or not, in theory it should auto update when the MAX POWER changes.

**Comment by agbaber** [comment]
Ok - I also had trouble getting it to update when switching between characters. Was also having trouble getting things like postmaster counts to update without a restart, but may have been related to the other issue(s) i was having.

**Comment by fcannizzaro** [comment]
When you switch character you need at least 30s to refresh the current data, I'll check this issue asap on another device. Sometimes the counter using the api is updated and then reverted to a previous state (it's a bit weird) .

**Comment by delphiactual** [comment]
It appears to not recover from screensaver maybe?

**Comment by agbaber** [comment]
Interesting, today I am getting a constant:

```
13:56:59.668                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_da235e0f73cad73e58f66afea9c7deaf>::operator ()(): The plugin 'DIM Stream Deck' exited normally with code 1
13:57:59.659                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_da235e0f73cad73e58f66afea9c7deaf>::()::<lambda_edf3f60a824e4535b7414c8c0c192809>::operator ()(): Restarting plugin 'DIM Stream Deck' after one minute
13:58:00.026                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_da235e0f73cad73e58f66afea9c7deaf>::operator ()(): The plugin 'DIM Stream Deck' exited normally with code 1
```
and none of the buttons are working. Maybe DIM changes?

**Comment by fcannizzaro** [comment]
wtf, I'm using it right now, but some actions are not updating..

**Comment by agbaber** [comment]
Rebooted the computer and it's working again - so bizarre!

**Comment by fcannizzaro** [comment]
#15
