### ISSUE TITLE
Stream Deck + doesn't show numbers

### ISSUE THREAD

**Issue by MichaelTorfs** [fcannizzaro/com.dim.streamdeck#37]
Hi, I'm a new user of the plugin, just bought a Stream Deck +.
You should authenticate by pressing the right number.

But the numbers are not shown on the Stream Deck.

Could that be an issue that the new Stream Deck + is not yet supported?
Or am I doing something wrong?

Kind regards,
Michael

**Comment by MichaelTorfs** [comment]
I found out that during the plugin install you get the question to install the profiles.
I answer yes, but they don't appear under profiles

**Comment by MichaelTorfs** [comment]
Now I also managed to import the profiles, but I still don't see numbers.
I see 3 profiles and the seem to be named for specific StreamDeck models: Normal, mini and XL.

Should this work, or does the StreamDeck + need a separate profile?

**Comment by zacgoodwin** [comment]
Same issue; Stream Deck Plus may be too new ( ; _ ; )

**Comment by zacgoodwin** [comment]
@MichaelTorfs Destiny 2's API is down so DIM isn't working either. Everything should be back up around Tuesday.

**Comment by zacgoodwin** [comment]
Now that things are working, I also can not get it to work on the Stream Deck Plus

**Comment by fcannizzaro** [comment]
Fixed also for SD+ with next DIM and Elgato store update (for newer issues go to https://github.com/dim-stream-deck/com.dim.streamdeck)
