### ISSUE TITLE
Fixes for 'connection with the DIM Stream deck Extension was not detected'

### ISSUE THREAD

**Issue by Heronemau5** [fcannizzaro/com.dim.streamdeck#4]
Here is what I have so far:

>App installed form stream deck store
>extension installed in opera
>all items in bungie.net privacy checkmarked
>restarted browser, stream deck app
>have DIM open in the browser as well
>same steps taken in chrome, same results

First attached image should show both Chrome and Opera open side-by-side with the extension page showing it is installed and the stream deck app in the foreground with the error.
Second attached image should show my bungie settings
Third and Fourth are the respective "Manage Extension" pages in chrome and opera that show the app installed and turned on
Final attached image is my streamdeck version and firmware, of which streamdeck says I am up to date when I check

![image](https://user-images.githubusercontent.com/23319434/155361075-43e1b47f-35b1-48a6-b2b8-a69056d8a159.png)
![image](https://user-images.githubusercontent.com/23319434/155361270-c4382150-ec68-4afe-a25c-0696a5d244d3.png)
![image](https://user-images.githubusercontent.com/23319434/155361459-0ce6ddce-8fc5-475a-9030-b2e0259d6eae.png)
![image](https://user-images.githubusercontent.com/23319434/155361385-fb3a36f8-54b8-434a-81ad-6a34923883e8.png)
![image](https://user-images.githubusercontent.com/23319434/155361888-a9dc7c32-ce67-404d-9241-e715a26009d1.png)

Is there something I may be missing here? only thing I have not yet tried is a reboot because this is a remote pc

**Comment by fcannizzaro** [comment]
Hi, it seems the plugin on the stream deck never started, can you check the logs ?

- can you see if after the plugin's installation there is a NodeEngine-16.0.0.exe executable in `%appdata%/Elgato/StreamDeck` ?
- can you check if NodeEngine-16.0.0.exe is running in the task manager ?

It should be as below

![image](https://user-images.githubusercontent.com/6225939/155494280-968d3b7c-e652-4e08-af9f-e45e4dc6c070.png)

**Comment by oneole** [comment]
do we need install nodejs? i have the same problem

**Comment by oneole** [comment]
it's work now. thank u so much! @delphiactual

**Comment by Heronemau5** [comment]
> Hi, it seems the plugin on the stream deck never started, can you check the logs ?
> 
> * can you see if after the plugin's installation there is a NodeEngine-16.0.0.exe executable in `%appdata%/Elgato/StreamDeck` ?
> * can you check if NodeEngine-16.0.0.exe is running in the task manager ?
> 
> It should be as below
> 
> ![image](https://user-images.githubusercontent.com/6225939/155494280-968d3b7c-e652-4e08-af9f-e45e4dc6c070.png)
Which log do you need me to check into? the NodeEngine exe exists in that folder but wasn't running in task manager until I launched the .exe. Even with the exe running I closed and reopened the StreamDeck app and no fix.

**Comment by fcannizzaro** [comment]
> ![image](https://user-images.githubusercontent.com/4798491/155549601-b9f1a449-2763-451e-be5b-0d74e39f4a07.png)
> 
> EDIT: I had to delete `NodeEngine-16.0.0.exe` and let it get re-installed automatically to fix my issue.

so there is an issue with the first auto-download of the Node binary. A possible fix is to check the shasum of the binary and re-download if something is broken.

@Heronemau5 can you check if the NodeEngine is broken or not ?

**Comment by Heronemau5** [comment]
> > ![image](https://user-images.githubusercontent.com/4798491/155549601-b9f1a449-2763-451e-be5b-0d74e39f4a07.png)
> > EDIT: I had to delete `NodeEngine-16.0.0.exe` and let it get re-installed automatically to fix my issue.
> 
> so there is an issue with the first auto-download of the Node binary. A possible fix is to check the shasum of the binary and re-download if something is broken.
> 
> @Heronemau5 can you check if the NodeEngine is broken or not ?

I don't know how to do that tbh. I did do as your quotereply mentioned and deleted the .exe and then relaunched StreamDeck so it redownloaded that file and no fix

**Comment by misterburnz** [comment]
I seem to be hitting the same issue here. Extension installed on Chrome, logged into DIM but nothing is connecting. I've tried deleting the NodeEngine.exe and having it re-add itself, but I am still hitting this issue.  Any thoughts?

**Comment by stayupthetree** [comment]
I really wanted this to work, but am running into the same issue.

**Comment by dryles** [comment]
I'm guessing it didn't completely install for me.
The plugin appeared in stream deck  but never tried to connect.
I had to close and reopen the stream deck app before it started working.

**Comment by fcannizzaro** [comment]
#15
