### ISSUE TITLE
It's connected, but it doesn't work.

### ISSUE THREAD

**Issue by oneole** [fcannizzaro/com.dim.streamdeck#6]
Nothing shows up.
Here's the log file.
[StreamDeck0.log](https://github.com/fcannizzaro/com.dim.streamdeck/files/8143742/StreamDeck0.log)

![image](https://user-images.githubusercontent.com/43529206/155775251-31b551cf-2b2f-4844-9239-143f8b0153bc.png)

**Comment by oneole** [comment]
not only battle pass level

**Comment by vVLANGERVv** [comment]
I have noticed that from time to time I have to exit the Stream Deck (aka restart the app or my PC) then Plugin reconnects/re-establishes itself... Not a pure fix, but at least a work around...

**Comment by oneole** [comment]
> I am trying all sorts of things. Nothing works. When I first installed the plugin.. and selected the first icon I tried which was Refresh, nothing happened. I added the Open DIM icon and that took me to the project page one time only. Now.. it does nothing. None of the icons change at all in my SD XL. I DO see that when I try to use one of the character icons.. it DOES correctly list my 3 characters with their races.
> 
> The extension "fades" (disables) all the time. The only time I saw it light up as if it were active is when I actually go to the DIM web site (https://app.destinyitemmanager.com). Soon as I switch tabs.. its dimmed again.
> 
> I love this idea.. but unclear what is going on. Does this plugin just make requests (via the js plugin code) to the DIM API?

Same situation as mine

**Comment by hillmanation** [comment]
Work around for this issue that I have found is to run your Stream Deck application as Administrator. There seems to be a permissions issue with the plugin not being about to access the websocket port otherwise from what I can tell.

**Comment by fcannizzaro** [comment]
#15
